"""Resolves a class's constructor parameter types, once, for @Service/@Singleton registration."""

from __future__ import annotations

import inspect
import types
import typing
from dataclasses import dataclass, field
from typing import Any, Callable

from inito.di.factory import Factory
from inito.exceptions.errors import DependencyRegistrationError
from inito.metadata.class_metadata import METADATA_ATTRIBUTE
from inito.reflection.introspection import _self_reference_injected

_UNION_TYPE = getattr(types, "UnionType", None)
"""types.UnionType (X | Y's runtime type) only exists on Python 3.10+."""


@dataclass(frozen=True)
class Qualifier:
    """Names the desired implementation of an Annotated dependency.

    Use as ``Annotated[Repo, Qualifier("postgres")]`` to autowire the service
    registered with ``@Service(qualifier="postgres")`` when several implement
    the same base type. A bare string in the ``Annotated`` metadata
    (``Annotated[Repo, "postgres"]``) is accepted too.
    """

    name: str


def registrable_type(type_hint: Any) -> Any:  # noqa: ANN401 -- accepts/returns an arbitrary type hint
    """Reduce a hint to its autowire lookup type: strip Annotated, then Optional.

    ``Annotated[X, ...]`` -> ``X`` (the metadata is read separately by
    ``qualifier_of``); ``Optional[X]``/``X | None`` -> ``X`` (Python <= 3.10 also
    wraps a bare ``X = None`` parameter as ``Optional[X]``, so unwrapping keeps
    resolution consistent). Broader unions are left as-is - no single type to
    autowire.
    """
    if hasattr(type_hint, "__metadata__"):
        type_hint = type_hint.__origin__
    origin = typing.get_origin(type_hint)
    if origin is typing.Union or (_UNION_TYPE is not None and origin is _UNION_TYPE):
        args = [arg for arg in typing.get_args(type_hint) if arg is not type(None)]
        if len(args) == 1:
            return args[0]
    return type_hint


def qualifier_of(type_hint: Any) -> str | None:  # noqa: ANN401 -- arbitrary annotation
    """Return the qualifier name in an Annotated hint's metadata, if any."""
    for item in getattr(type_hint, "__metadata__", ()):
        if isinstance(item, Qualifier):
            return item.name
        if isinstance(item, str):
            return item
    return None


def factory_target(type_hint: Any) -> type | None:  # noqa: ANN401 -- arbitrary annotation
    """Return X when type_hint is ``Factory[X]`` (X a class), else None."""
    if typing.get_origin(type_hint) is Factory:
        args = typing.get_args(type_hint)
        if args and isinstance(args[0], type):
            return args[0]
    return None


@dataclass(frozen=True)
class Dependency:
    """A single constructor parameter's resolved type and whether it has a default value.

    ``registrable`` is the autowire lookup key - ``type_hint`` with any
    ``Optional``/``X | None`` wrapper stripped - computed once here at
    registration time rather than on every ``Container.get()`` resolution,
    keeping annotation inspection to decoration time only. It is derived
    from ``type_hint`` (not a separate constructor argument), so every
    ``Dependency(type_hint, has_default)`` call site stays unchanged and
    the two fields can never disagree.
    """

    type_hint: Any
    has_default: bool
    registrable: Any = field(init=False, compare=False)
    qualifier: str | None = field(init=False, compare=False)
    factory_target: type | None = field(init=False, compare=False)

    def __post_init__(self) -> None:
        """Derive and cache the autowire key, qualifier, and factory target, once."""
        object.__setattr__(self, "registrable", registrable_type(self.type_hint))
        object.__setattr__(self, "qualifier", qualifier_of(self.type_hint))
        object.__setattr__(self, "factory_target", factory_target(self.type_hint))


def resolve_constructor_dependencies(cls: type) -> dict[str, Dependency]:
    """Return {param_name: Dependency} for every __init__ parameter of cls except self.

    Resolved once, at @Service/@Singleton registration (decoration) time - never
    per Container.get() call. Every parameter must be type-annotated - either on
    __init__ itself, or (for an __init__ generated by another inito decorator,
    e.g. @RequiredArgsConstructor/@AllArgsConstructor/@Data/@NoArgsConstructor,
    whose generated source carries no annotations at all) via that decorator's
    already-cached ClassMetadata, which @Service reuses rather than re-deriving.
    A class with no custom __init__ has no dependencies.
    """
    # Walked via __mro__/__dict__ rather than `cls.__init__` - mypy flags the latter as an
    # unsound instance-attribute access on a `type` value, even though it's a class here.
    init = next(
        (klass.__dict__["__init__"] for klass in cls.__mro__ if "__init__" in klass.__dict__),
        object.__init__,
    )
    if init is object.__init__:
        return {}
    try:
        with _self_reference_injected(cls):
            hints = typing.get_type_hints(init, include_extras=True)
    except NameError as error:
        raise DependencyRegistrationError(
            f"Could not resolve constructor type hints for {cls.__qualname__!r}: {error}"
        ) from error
    hints.pop("return", None)
    field_types = _cached_field_types(cls)
    return _dependencies_from_signature(init, hints, field_types, cls.__qualname__, skip_self=True)


def resolve_provider_dependencies(fn: Callable[..., Any]) -> dict[str, Dependency]:
    """Return {param_name: Dependency} for a @Resource generator provider's parameters.

    Resolved once, at registration time. Every parameter must be type-annotated;
    the provider function has no ``self`` and no ClassMetadata fallback.
    """
    try:
        hints = typing.get_type_hints(fn, include_extras=True)
    except NameError as error:
        raise DependencyRegistrationError(
            f"Could not resolve parameter type hints for {fn.__qualname__!r}: {error}"
        ) from error
    hints.pop("return", None)
    return _dependencies_from_signature(fn, hints, {}, fn.__qualname__, skip_self=False)


def _dependencies_from_signature(
    func: Callable[..., Any],
    hints: dict[str, Any],
    field_types: dict[str, Any],
    owner: str,
    *,
    skip_self: bool,
) -> dict[str, Dependency]:
    params = inspect.signature(func).parameters
    dependencies: dict[str, Dependency] = {}
    for name, param in params.items():
        if skip_self and name == "self":
            continue
        if name in hints:
            type_hint = hints[name]
        elif name in field_types:
            type_hint = field_types[name]
        else:
            raise DependencyRegistrationError(
                f"{owner} parameter {name!r} has no type annotation; DI requires every "
                "injected parameter to be annotated."
            )
        dependencies[name] = Dependency(type_hint, param.default is not inspect.Parameter.empty)
    return dependencies


def _cached_field_types(cls: type) -> dict[str, Any]:
    """Return {field_name: type_hint} from cls's own cached ClassMetadata, if any.

    Only cls.__dict__ (never inherited via getattr), matching
    MetadataExtractor.extract's own rule - a subclass that wasn't itself
    decorated shouldn't silently inherit a base class's field types.
    """
    metadata = cls.__dict__.get(METADATA_ATTRIBUTE)
    if metadata is None:
        return {}
    return {field.name: field.type_hint for field in metadata.fields}
